### PR TITLE
ADC Driver with test code for P1.0

### LINKED ISSUE #12: MSP ADC Driver
Just be able to implement basic ADC operations. AKA simply just be able to read analog from a pin

### PR DESCRIPTION
**Pull request by Siri2K**
## Description (tell us what you changes or added or removed please)
Setup ADC driver for A0 (Pin 1.0). Code ADC codes provide ADC Intiialize, Start, Stop, Enable and ADC reding functionality. Before Merging, please remove the test.c code as it is simply a test code, not an implementation

## How to test (if any tests done)
1) Open CCS C Compiler
2) Start new project 
3) Choose MSP430F5659
4) Choice Empty project with main.c
5) Copy code to empty project
6) Copy test.c to main.c
7) Build and run code

Issue: #12

## Checklist
- [x] Code Compiles
- [x] Did you add any comments
- [ ] Did you test it at all ?! Good Boy/Girl

### CODE REVIEW

**Comment by Siri2K** [comment]
@hanlee53, @jasminetheepeach.  I'm not gonna be able to make it this weekend, can you test & review the code?  There's already a test Code include in the driver code I made. After confirming that the code works on the board, delete the test.c code. 

test.c is just code to display the readings. Just checks if the adc driver code and ADC readings works.

**Comment by jasminetheepeach** [comment]
@Siri2K @hanlee53 I went to the lab today but it was locked so I couldn't test the code. Could we meet up next Saturday maybe?

**Comment by Siri2K** [comment]
Board at the lab is MSP430FR5969. adc.c needs to be corrected for the correct board

**Comment by Siri2K** [comment]
@hanlee53, @jasminetheepeach fixed the code. It's programed for the right board now. Just need to test it. @jasminetheepeach If I remeber, we said we were gonna test at October 18 at 1pm right?

**Comment by silvehh** [comment]
No need for this merge as the ADC driver has been already completed (sorry i saw this merge request after i merged my finished code)

**Pull request closed without merging**
